### ISSUE TITLE
quickcheck conformity

### ISSUE THREAD

**Issue by teto** [erikd/wide-word#35]
Would it be possible to support more recent quickcheck ? I've tried jailbreaking on nixos-unstable but tests fail with:
```
Preprocessing test suite 'laws' for wide-word-0.1.1.0..
Building test suite 'laws' for wide-word-0.1.1.0..
test/laws.hs:54:5: error:
    • Variable not in scope: numLaws :: Proxy a -> Laws
    • Perhaps you meant ‘enumLaws’ (imported from Test.QuickCheck.Classes)
   |
54 |   , numLaws
   |     ^^^^^^^

note: keeping build directory '/tmp/nix-build-wide-word-0.1.1.0.drv-1'
```
And without jailbreaking:
```

CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:950:20 in Cabal-2.4.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:460:12 in Cabal-2.4.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.4.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.4.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.4.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.4.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
quickcheck-classes >=0.6.3 && <0.7.0
```

**Comment by erikd** [comment]
"Jailbeaking"? Where is the jail? You mean NixOs?

The current Hackage version of `wide-word` uses `QuickChck >= 2.9.2       && < 2.14` and the latest version of `QuickCheck` on Hackage is `2.13.2`.

The ticket says `QickCheck` but the error message is `quickcheck-classes >=0.6.3 && <0.7.0` and the current Hackage version is `0.6.4.0`, so I have not idea what this issue is about. 

So then I ran `cabal update && cabal build all && cabal test all -j` and everything worked just as it should. Could what you are seeing be a Nix only problem?

You need to investigate this further yourself. When you get the bottom of the issue it would probably be easier to submit a PR than submitting an issue.

**Comment by teto** [comment]
nixos-unstable quickcheck classes version is too old: `       version = "0.6.1.0";` so not your fault sry. I will fix it. Thanks.
